### ISSUE TITLE
Re-enable linking to results?

### ISSUE THREAD

**Issue by j9t** [projectwallace/css-code-quality#8]
In the (distant?) past, one could navigate right to code quality analysis results, as with “[https://www.projectwallace.com/css-code-quality?url=https%3A%2F%2Fexample.com%2F](https://www.projectwallace.com/css-code-quality?url=https%3A%2F%2Fexample.com%2F)”.

This doesn’t work anymore, slowing use of the tool down (probably the intention behind the change?), and reducing its utility in tools like [Frontend Dogma’s Site Check](https://frontenddogma.com/tools/check/).

It would be great if this option was supported again—perhaps through a compromise, i.e., prefilling the URL field with the respective value.

(For Frontend Dogma, I may need to pull the CSS Code Quality tool—and re-check other Project Wallace tools—as it’s not meeting my own users’ expectations anymore. That doesn’t need to concern you, and it’s not meant to put pressure on this, but just to be open about it as there’s no value to be featured by Site Check if users need to re-enter the URL.)

**Comment by bartveneman** [comment]
To be honest I can't really remember why I pulled that URL-prefill out of the site. I remember it was a bit slow to prefill the URL sometimes and the code I had in place wasn't too great (parsing/validating URL's: meh). I'll have a look to add it back, because I think it makes sense to 'hotlink' to a certain URL for easy sharing.

**Comment by bartveneman** [comment]
@j9t Shall I also add URL-prefill support to https://www.projectwallace.com/get-css?

**Comment by j9t** [comment]
@bartveneman, thanks for considering, and yes—though for purposes of Wallace being featured on [Frontend Dogma](https://frontenddogma.com/), re-enabling this for [Analyze CSS](https://www.projectwallace.com/analyze-css) would be even more impactful (it’s being linked by Site Check, too).

**Comment by bartveneman** [comment]
Pushed the changes to production, enjoy!

**Comment by j9t** [comment]
Seems to work nicely! Cheers!
